[package]
name = "rtun"
version = "0.1.0"
edition = "2021"
authors = ["Agustí Moll"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
tokio = { version = "1.37.0", features = ["full"] }
